// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjUT8iC_Q1Al21NTpsgkKN83yggH67arw',
    appId: '1:611426911388:web:56c77659edda8005d25959',
    messagingSenderId: '611426911388',
    projectId: 'vet-digital',
    authDomain: 'vet-digital.firebaseapp.com',
    storageBucket: 'vet-digital.appspot.com',
    measurementId: 'G-J2RJD18393',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK7wfsPIHOqJnJSKSFQDze5SsGp482QtM',
    appId: '1:611426911388:android:eea3e24b8adb1f26d25959',
    messagingSenderId: '611426911388',
    projectId: 'vet-digital',
    storageBucket: 'vet-digital.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd-bpMAV_JvdeKQjlyDil3ef-seaPqGJo',
    appId: '1:611426911388:ios:3d00fd4d84ee8501d25959',
    messagingSenderId: '611426911388',
    projectId: 'vet-digital',
    storageBucket: 'vet-digital.appspot.com',
    iosClientId: '611426911388-nb562cbfp4do73cmtrgu4lvtkfcaf58h.apps.googleusercontent.com',
    iosBundleId: 'com.vetdigital.vetdigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd-bpMAV_JvdeKQjlyDil3ef-seaPqGJo',
    appId: '1:611426911388:ios:3d00fd4d84ee8501d25959',
    messagingSenderId: '611426911388',
    projectId: 'vet-digital',
    storageBucket: 'vet-digital.appspot.com',
    iosClientId: '611426911388-nb562cbfp4do73cmtrgu4lvtkfcaf58h.apps.googleusercontent.com',
    iosBundleId: 'com.vetdigital.vetdigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjUT8iC_Q1Al21NTpsgkKN83yggH67arw',
    appId: '1:611426911388:web:9f96a61b6304bf39d25959',
    messagingSenderId: '611426911388',
    projectId: 'vet-digital',
    authDomain: 'vet-digital.firebaseapp.com',
    storageBucket: 'vet-digital.appspot.com',
    measurementId: 'G-LX47GTVJWX',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCjUT8iC_Q1Al21NTpsgkKN83yggH67arw',
    appId: '1:611426911388:web:596412e3ba3c84c6d25959',
    messagingSenderId: '611426911388',
    projectId: 'vet-digital',
    authDomain: 'vet-digital.firebaseapp.com',
    storageBucket: 'vet-digital.appspot.com',
    measurementId: 'G-6ZW2E9BBCP',
  );
}
